name: GitHub Profile 3D Contrib

on:
  schedule: # 03:00 UTC == 22:00 PST
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write  # This is the key fix!

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: KrishnamohanKapri
      
      - name: Commit & Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "generated" || exit 0
          git push
